In [1]:
import numpy as np
import matplotlib.pyplot as plt
size = 30

In [8]:
def distEuclid(x,y):
    dis =  np.sqrt(np.sum((x-y)**2))
    return dis
'''x = np.array([4,2,3])
y = np.array([0,2,0])
distEuclid(x,y) # 5.0'''

In [15]:
def genDataset(n,dim):
    data = []
    while len(data) < n:
        p = np.around(np.random.rand(dim)*size, decimals=2)
        data.append(p)
    return data
    

In [16]:
genDataset(10,3)

[array([21.5 , 11.7 , 11.13]),
 array([ 9.3 , 24.74,  4.64]),
 array([24.48, 14.97, 15.49]),
 array([ 5.58, 23.45,  7.08]),
 array([15.74, 26.94,  5.14]),
 array([10.89, 13.74, 13.27]),
 array([17.12, 21.93, 17.44]),
 array([16.38,  6.1 , 11.59]),
 array([27.96,  4.76, 19.08]),
 array([13.23, 14.04, 12.89])]

In [29]:
def isNeighbor(x,y,eps):
    return distEuclid(x,y)<=eps
#get dots in one's neighbor domain
def getSeedPos(pos,data,eps):
    seed = []
    for p in range(len(data)):
        if isNeighbor(data[p],data[pos],eps):
            seed.append(p)
    return seed
#get core point list
def getCorePointsPos(data,eps,minpts):
    cpoints = []
    for pos in range(len(data)):
        if len(getSeedPos(pos,data,eps)) >= minpts:
            cpoints.append(pos)
            
    return cpoints
def getCluster(data,eps,minpts):
    corePos = getCorePointsPos(data,eps,minpts)
    unvisited = list(range(len(data)))
    cluster = {}
    num = 0
    for pos in corePos:
        if pos not in unvisited:
            continue
        clusterpoint = []
        clusterpoint.append(pos)
        seedlist = getSeedPos(pos,data,eps)
        unvisited.remove(pos)
        while seedlist:
            p = seedlist.pop(0)
            if p not in unvisited:
                continue
            unvisited.remove(p)
            clusterpoint.append(p)
            if p in corePos:
                seedlist.extend(getSeedPos(p,data,eps))
        cluster[num] = clusterpoint
        num+=1
    cluster["noisy"] = unvisited
    return cluster


In [47]:
data = np.array(genDataset(80,3))


In [49]:
cl = getCluster(data,7,2)
cl

{0: [0,
  40,
  46,
  56,
  62,
  63,
  51,
  53,
  67,
  45,
  74,
  16,
  43,
  69,
  73,
  7,
  41,
  33,
  14,
  58,
  77,
  1,
  44,
  50,
  72,
  65,
  68,
  34,
  4,
  5,
  23,
  38,
  57,
  75,
  47,
  25,
  21,
  10,
  52,
  64,
  60,
  9,
  22,
  49,
  59,
  71,
  76,
  12,
  30,
  35],
 1: [2, 78, 36, 42, 55, 70, 79, 18, 3, 24, 19, 61],
 2: [6, 27],
 3: [8, 32, 39, 66],
 4: [11, 13, 37],
 5: [15, 54, 28],
 6: [17, 20],
 7: [26, 29, 31, 48],
 'noisy': []}

In [38]:
data

array([[19.76, 18.96, 24.09],
       [ 7.36, 22.96,  6.88],
       [17.38, 24.6 , 13.  ],
       [14.83, 18.45, 26.63],
       [ 2.36, 28.87,  7.55],
       [22.  , 25.14, 21.32],
       [ 6.76, 13.19,  3.27],
       [29.23, 19.39,  5.16],
       [17.13, 22.52,  3.58],
       [29.8 , 20.51, 11.43],
       [ 0.66, 13.97, 21.55],
       [18.62,  2.78,  5.17],
       [ 7.69, 22.48, 27.23],
       [ 1.42, 15.7 , 28.61],
       [19.05,  9.36,  9.21],
       [21.55, 14.39, 27.32],
       [16.49, 15.28, 13.38],
       [29.66, 25.88, 18.73],
       [ 2.89,  0.88, 23.17],
       [11.87, 14.11,  4.36],
       [ 7.06, 10.84, 13.96],
       [24.9 , 22.18, 14.95],
       [27.5 ,  3.04, 23.02],
       [12.26, 15.24,  3.37],
       [19.52, 28.98,  6.5 ],
       [10.38, 24.84,  8.7 ],
       [19.96, 20.34, 28.34],
       [ 1.4 , 18.21,  4.69],
       [ 8.95, 16.63, 11.89],
       [15.48, 28.44, 20.23],
       [21.07, 19.8 ,  2.34],
       [15.22, 13.14, 15.9 ],
       [26.73, 15.19, 18.87],
       [26